server:
  port: 8002
  
order:
  commodityName:
    zh: "五花肉"
    en: "Streaky Pork"
  price: 50.0


warp:
  service:
    prefix: "这是头"
    suffix: "这是尾巴"
#必须配置
#指定nameServer
rocketmq:
  nameServer: 127.0.0.1:9876
  producer:
    group: "my-group"
    send-message-timeout: 300000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-async-failed: 0
    retry-next-server: true
    retry-times-when-send-failed: 2
