server:
  port: 8002
  
order:
  commodityName:
    zh: "五花肉"
    en: "Streaky Pork"
  price: 50.0

arch:
  mq:
    accesskey: ""
    secretkey: ""
    namesrvAddr: ""
ccvs:
  platform:
    mq:
      request.topic: TOPIC_CCSV_STANDARD_PLATFORM_SYNC_TEST
      response.topic: TOPIC_CCSV_STANDARD_PLATFORM_SYNC_RESPONSE_TEST
      callback.topic: TOPIC_CCSV_STANDARD_PLATFORM_CALLBACK_TEST
      response.groupid: GID_CCSV_SP_SYNC_RESPONSE_TEST
      callback.groupid: GID_CCSV_PLATFORM_CALLBACK_TEST #GID_CCSV_STANDARD_PLATFORM_CALLBACK



warp:
  service:
    prefix: "这是头"
    suffix: "这是尾巴"
#必须配置
#指定nameServer
#rocketmq:
#  nameServer: 127.0.0.1:9876
#  producer:
#    group: "my-group"
#    send-message-timeout: 300000
#    compress-message-body-threshold: 4096
#    max-message-size: 4194304
#    retry-times-when-send-async-failed: 0
#    retry-next-server: true
#    retry-times-when-send-failed: 2


spring:
  application:
    name: sentinel-demo

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    #配置sentinel客户端，注册该项目进控制台里
    sentinel:
      eager: true
      transport:
        #配置Sentin dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
        port: 8719
      #nacos  从nacos拉取数据需要配置
      datasource:
        #名称随意
        flow:
          nacos:
            server-addr: localhost:8848
            namespace: sentinel-rule
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
